version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers: [ nwtgck ]
  assignees: [ nwtgck ]
- package-ecosystem: gomod
  directory: "/go"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers: [ nwtgck ]
  assignees: [ nwtgck ]
- package-ecosystem: gitsubmodule
  directory: "/go/golang-crypto"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers: [ nwtgck ]
  assignees: [ nwtgck ]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers: [ nwtgck ]
  assignees: [ nwtgck ]
